---
################ setup_system ##################

- name: Create users on hosts
  hosts: nodes
  become: True
  gather_facts: no
  roles:
      - { role: create_users }
      - { role: config_ssh }
      - { role: config_dns }
      - { role: config_ntp }

