---
################ setup_system ##################
- name: Perform setup of host
  hosts: nodes
  become: True
  gather_facts: no
  roles:
      - { role: create_users }
      - { role: config_ssh }
      - { role: config_dns }
      - { role: config_ntp }
      - { role: install_apps }

