---
- name: include vars
  include_vars:
    file: ../../settings.yml
    name: settings

- name: Configure NTP community
  community.general.timezone:
    name: "{{ settings.timezone }}"

- name: Make sure timesyncd is stopped
  systemd:
    name: systemd-timesyncd.service
    state: stopped

- name: update ntp primary server
  ansible.builtin.replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#NTP=.*'
    replace: "NTP={{ settings.ntp_svr_primary }}"

- name: update ntp fallback server
  ansible.builtin.replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#FallbackNTP=.*'
    replace: "FallbackNTP={{ settings.ntp_svr_fallback }}"

- name: Make sure timesyncd is started
  systemd:
    name: systemd-timesyncd.service
    state: started

- name: Test that time is synced
  shell: timedatectl | grep "System clock synchronized" | awk '{print$4}'
  register: result
  failed_when: "'hello' in result.stdout_lines"

- name: output result must be "yes"
  debug:
    msg: "{{ result.stdout_lines }}"
