- name: include vars
  include_vars:
    file: ../../settings.yml
    name: settings

- hosts: all
  roles:
  - systemd-timesyncd
    timesync_timezone: "{{ settings.timesync_timezone }}" 
    timesync_ntp_hosts:
      - time.cloudflare.com
      - time.google.com