
# - name: Install the dependencies of Docker CE
#   apt:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - 'apt-transport-https'
#     - 'ca-certificates'
#     - 'curl'
#     - 'software-properties-common'

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present and ansible_distribution == 'Ubuntu'

- name: Add Docker stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" and ansible_distribution == 'Ubuntu'

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present and ansible_distribution == 'Debian'

- name: Add Docker stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" and ansible_distribution == 'Debian'

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: true
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    update_cache: true
    state: present

- name: Create the Docker group
  group:
    name: docker
    state: present

- name: Add users to the Docker group
  user:
    name: "{{ item.username }}" 
    groups: docker
    append: yes
  with_items: "{{ users }}"

- name: Containers internal network
  docker_network:
    name: "{{ dockernet }}"
    attachable: "yes"
    ipam_config:
    - subnet: 172.3.27.0/24
      gateway: 172.3.27.2
      iprange: 172.3.27.0/26
      aux_addresses:
        host1: 172.3.27.3
        host2: 172.3.27.4
 