---
- name: create .zshrc
  file:
    path: /home/{{ settings.username }}/.zshrc
    state: touch
  with_items: "{{ settings.username }}"

- name: Add source to .zshrc
  lineinfile:
    path: /home/{{ settings.username }}/.zshrc
    line: 'source /usr/share/zsh-config/.zshrc'
    insertbefore: BOF
  with_items: "{{ settings.username }}"

- name: Install zsh
  apt:
    name: zsh
    state: present
