---
#settings for deployments

username: mellonaut
hostname: wintermute

ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
network_interface_name: ens33
dns_servers: "[9.9.9.9, 10.215.0.4]"
timezone: America/New_York
ntp_svr_primary: time-a-g.nist.gov
ntp_svr_fallback: time-b-g.nist.gov


my_ssh_pub_key: "~/.ssh/id_ed25519.pub"

timesync_timezone: America/New_York

zerotier_network_id: "d3ecf5726dae7524"

      # ZSH Settings
      zsh_shared: yes
      
      # Docker Settings
      dockernet: "docker"
      docker_home_dir: '/opt/docker'

      # Pip Settings
      pip_install_packages:
        - name: docker
      pip_executable: pip3
      pip_package: python3-pip

      # NTP
      ntp_timezone: 'America/New_York'

      # Traefik
      traefik_dir: "/opt/docker/traefik"
      traefik_network: "docker"
      traefik_hostname: "traefik"
      traefik_add_volumes:
      - "{{ traefik_dir }}/acme:/etc/traefik/acme"
      - "{{ traefik_dir }}/log:/etc/traefik/log"
      - "/etc/traefik/elastic_traefik.yml:/etc/traefik/elastic_traefik.yml"
      traefik_ports:
        - '80:80'
        - '443:443'
        - '127.0.0.1:8080:8080'

      traefik_labels:
        traefik.http.routers.traefik.tls: "true"
        traefik.frontend.passHostHeader: "true"

      traefik_confkey_api:
        insecure: true
        dashboard: true

      traefik_confkey_serversTransport:
        insecureSkipVerify: true

      traefik_confkey_log: 
        filePath: "/etc/traefik/log/traefik.log"
        level: "INFO"

      traefik_confkey_accessLog:
        filePath: "/etc/traefik/log/access.log"
        bufferingSize: 100

      traefik_confkey_entryPoints:
        web_http:
          address: ':80'
          http:
            redirections:
              entryPoint:
                to: 'websecure'
                scheme: 'https'
        websecure:
          address: ':443'
        
      traefik_confkey_providers:
        file:
          filename: /etc/traefik/elastic_traefik.yml
          watch: true
      
      #Elastic
      elastic_cluster_name: "shrinebuilder"
      elastic_network_host: "0.0.0.0"
      elastic_discovery_type: "single-node"
      elasticsearch_username: "elastic"
      elasticsearch_password: "2v4233v434v324v324v"

      kibana_network_host: "0.0.0.0"
      xpack_encyption_key: "f2eJAt3zLQHiDqH4nDeb3d2KEhzeasiJ6UF4"